In [114]:
import pandas as pd

In [115]:
url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df=pd.read_csv(url,sep='\t')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [5]:
titanic='https://github.com/sehakflower/data/blob/main/titanic.xlsx?raw=true'
titanic=pd.read_excel(titanic,sheet_name='titanic3')
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

#Section 02. 데이터 처리
## 1. 데이터 살펴보기
### 앞뒤 데이터 보기: head, tail 함수

In [116]:
titanic_df.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [117]:
titanic_df.tail(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

###데이터 개수/형태 확인하기: len/shape 함수

In [118]:
len(titanic_df)

156

In [119]:
titanic_df.shape

(156, 12)

###데이터의 기본 통계치 보기: describe 함수

In [120]:
titanic_df.describe( )

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

###결측치와 데이터형 확인하기: info 함수

In [121]:
titanic_df.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    object
 4   Sex          156 non-null    object
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    object
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object
 11  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB

##2. 열/행 정리하기
###열 이름 변경하기

In [122]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [123]:
new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns=new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [124]:
titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

###데이터프레임 복사하기

In [125]:
copy_titanic_df=titanic_df.copy( )
copy_titanic_df.head( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

###행 추가하기

In [126]:
copy_titanic_df.append({'passengerId':1, 'survived':1, 'pclass':1, 'name':1, 'sex':1,
'age':1, 'sibsp':1, 'parch':1, 'ticket':1, 'fare':1, 'cabin':1,
'embarked':1}, ignore_index=True)

<ipython-input-126-d56d4ab6a6ae>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  copy_titanic_df.append({'passengerId':1, 'survived':1, 'pclass':1, 'name':1, 'sex':1,

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
156,1,1,1,1,1,1.0,1,1,1,1.0000,1,1

In [127]:
copy_titanic_df.tail( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [128]:
copy_titanic_df=copy_titanic_df.append({'passengerId':1, 'survived':1, 'pclass':1,
'name':1, 'sex':1, 'age':1, 'sibsp':1, 'parch':1, 'ticket':1, 'fare':1, 'cabin':1,
'embarked':1}, ignore_index=True)
copy_titanic_df.tail( )

<ipython-input-128-247b0f2f3351>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  copy_titanic_df=copy_titanic_df.append({'passengerId':1, 'survived':1, 'pclass':1,

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
156,1,1,1,1,1,1.0,1,1,1,1.0000,1,1

###열 추가하기

In [129]:
copy_titanic_df['gender']=1
copy_titanic_df.tail( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,gender
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S,1
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S,1
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S,1
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C,1
156,1,1,1,1,1,1.0,1,1,1,1.0000,1,1,1

In [130]:
copy_titanic_df.loc[copy_titanic_df['sex']=='female', 'gender']=0
copy_titanic_df.head( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

##3. 인덱스 정리하기
###index 속성

In [131]:
titanic_df.index

RangeIndex(start=0, stop=156, step=1)

###values 속성

In [132]:
titanic_df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [154, 0, 3, ..., 14.5, nan, 'S'],
       [155, 0, 3, ..., 7.3125, nan, 'S'],
       [156, 0, 1, ..., 61.3792, nan, 'C']], dtype=object)

###열 추출하기

In [133]:
age=titanic_df['age'] # Series 객체는 1차원 배열(ndarray)과 호환됨
print(type(age))
age

<class 'pandas.core.series.Series'>

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

##4. 데이터 정렬하기
###인덱스 기준으로 정렬하기

In [134]:
titanic_df.sort_index( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

###열 기준으로 정렬하기

In [135]:
titanic_df.sort_values(by='age') # 오름차순 정렬
titanic_df.sort_values(by='age', ascending=False) # 내림차순 정렬

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [26]:
titanic_df.sort_values(by=['age', 'pclass']) # 오름차순 정렬
titanic_df.sort_values(by=['age', 'pclass'], ascending=False) # 내림차순 정렬

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C

##5. 데이터 가져오기
### 지정 범위의 행에서 데이터 가져오기

In [136]:
titanic_df[0:5] # titanic_df.head(  )와 실행 결과 동일함
titanic_df[0:1] # 첫 행만 가져오기
titanic_df[::3] # 3개씩 건너서 출력함
titanic_df[::-1] # 행의 순서를 거꾸로 출력함

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [137]:
titanic_df[0:5] # titanic_df.head(  )와 실행 결과 동일함

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

###단순 인덱스로 범위 지정해 데이터 가져오기

In [28]:
titanic_df[:3]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [138]:
titanic_df[::3] # 3개씩 건너서 출력함

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,18.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
33,34,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,10.5000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,7.8000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
57,58,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,2697,7.2292,NaN,C
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,315151,8.6625,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
93,94,0,3,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,20.5750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
99,100,0,2,"Kantor, Mr. Sinai",male,34.00,1,0,244367,26.0000,NaN,S
102,103,0,1,"White, Mr. Richard Frasar",male,21.00,0,1,35281,77.2875,D26,S
105,106,0,3,"Mionoff, Mr. Stoytcho",male,28.00,0,0,349207,7.8958,NaN,S
108,109,0,3,"Rekic, Mr. Tido",male,38.00,0,0,349249,7.8958,NaN,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C
114,115,0,3,"Attalah, Miss. Malake",female,17.00,0,0,2627,14.4583,NaN,C
117,118,0,2,"Turpin, Mr. William John Robert",male,29.00,1,0,11668,21.0000,NaN,S
120,121,0,2,"Hickman, Mr. Stanley George",male,21.00,2,0,S.O.C. 14879,73.5000,NaN,S
123,124,1,2,"Webber, Miss. Susan",female,32.50,0,0,27267,13.0000,E101,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
129,130,0,3,"Ekstrom, Mr. Johan",male,45.00,0,0,347061,6.9750,NaN,S
132,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.00,1,0,A/5. 3337,14.5000,NaN,S
135,136,0,2,"Richard, Mr. Emile",male,23.00,0,0,SC/PARIS 2133,15.0458,NaN,C
138,139,0,3,"Osen, Mr. Olaf Elon",male,16.00,0,0,7534,9.2167,NaN,S
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.00,0,0,347081,7.7500,NaN,S
144,145,0,2,"Andrew, Mr. Edgardo Samuel",male,18.00,0,0,231945,11.5000,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,34.3750,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.00,0,0,S.O.P. 1166,12.5250,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.50,0,2,A/5. 851,14.5000,NaN,S

###지정 범위의 열에서 데이터 가져오기

In [139]:
len(titanic_df.columns)

12

In [140]:
titanic_df[titanic_df.columns[0]] # 첫 번째(0번) 열을 1차원 배열의 Series 객체로 추출

0        1
1        2
2        3
3        4
4        5
      ...
151    152
152    153
153    154
154    155
155    156
Name: passengerId, Length: 156, dtype: int64

In [141]:
titanic_df[titanic_df.columns[11]] # 마지막 열을 1차원 배열의 Series 객체로 추출
# titanic_df[titanic_df.columns[-1]] # 혹은 [-1]로 표시

0      S
1      C
2      S
3      S
4      S
      ..
151    S
152    S
153    S
154    S
155    C
Name: embarked, Length: 156, dtype: object

###열 이름으로 데이터 가져오기

In [142]:
age=titanic_df['age']
print(type(age))

<class 'pandas.core.series.Series'>

In [143]:
titanic_df['age'] # 'age' 열을 1차원 배열인 Series 객체로 추출
titanic_df.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

###열 이름과 위치를 이용해 데이터 가져오기

In [144]:
print(titanic_df[titanic_df.columns[0]][0]) # 첫 번째 열의 첫 번째 값
print(titanic_df['age'][0]) # age 열의 첫 번째 값
print(titanic_df[titanic_df.columns[0]][2])
print(titanic_df[titanic_df.columns[-1]][0])
type(titanic_df[titanic_df.columns[0]][0]) # str

1
22.0
3
S

numpy.int64

In [35]:
titanic_df[titanic_df.columns[0]][2:6] # 2번부터 5번 행까지
titanic_df[titanic_df.columns[0]][:-1] # 마지막 행 제외
titanic_df[titanic_df.columns[0]][::3] # 3개의 step으로 슬라이싱
titanic_df[titanic_df.columns[0]][-1:] # 마지막 행만 추출
titanic_df[titanic_df.columns[0]][::-1] # 행을 역순으로 출력

155    156
154    155
153    154
152    153
151    152
      ...
4        5
3        4
2        3
1        2
0        1
Name: passengerId, Length: 156, dtype: int64

In [145]:
titanic_df[titanic_df.columns[0]][2:6] # 2번부터 5번 행까지

2    3
3    4
4    5
5    6
Name: passengerId, dtype: int64

In [146]:
titanic_df[titanic_df.columns[0]][:-1] # 마지막 행 제외

0        1
1        2
2        3
3        4
4        5
      ...
150    151
151    152
152    153
153    154
154    155
Name: passengerId, Length: 155, dtype: int64

In [147]:
titanic_df[['pclass', 'name', 'sex']] # DataFrame 추출
titanic_df[[titanic_df.columns[2],titanic_df.columns[3],titanic_df.columns[4]]]
 # DataFrame 추출

     pclass                                               name     sex
0         3                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         3                             Heikkinen, Miss. Laina  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4         3                           Allen, Mr. William Henry    male
..      ...                                                ...     ...
151       1                  Pears, Mrs. Thomas (Edith Wearne)  female
152       3                                   Meo, Mr. Alfonzo    male
153       3                    van Billiard, Mr. Austin Blyler    male
154       3                              Olsen, Mr. Ole Martin    male
155       1                        Williams, Mr. Charles Duane    male

[156 rows x 3 columns]

In [148]:
titanic_df[[titanic_df.columns[2],titanic_df.columns[3],titanic_df.columns[4]]][2:15:3]
# 슬라이싱

    pclass                                               name     sex
2        3                             Heikkinen, Miss. Laina  female
5        3                                   Moran, Mr. James    male
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
11       1                           Bonnell, Miss. Elizabeth  female
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female

In [149]:
print(titanic_df[titanic_df.columns[0]][0])
print(titanic_df[titanic_df.columns[0]][2])
# print(titanic_df[titanic_df.columns[0]][-1]) # 실행 시 오류 발생
type(titanic_df[titanic_df.columns[0]][0])

1
3

numpy.int64

###인덱스 이름을 기준으로 데이터 가져오기: loc 속성

In [150]:
titanic_df.loc[0]

passengerId                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [151]:
titanic_df.loc[0:5]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [152]:
titanic_df.loc[0:10:2]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [153]:
titanic_df.loc[:, 'age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [154]:
titanic_df.loc[:, ['age', 'sex']]

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
151  22.0  female
152  55.5    male
153  40.5    male
154   NaN    male
155  51.0    male

[156 rows x 2 columns]

In [155]:
titanic_df.loc[3:7, ['age', 'sex']]

    age     sex
3  35.0  female
4  35.0    male
5   NaN    male
6  54.0    male
7   2.0    male

In [156]:
titanic_df.loc[2:5, 'survived':'age']

,survived,pclass,name,sex,age
2,1,3,"Heikkinen, Miss. Laina",female,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0
5,0,3,"Moran, Mr. James",male,NaN

###인덱스 순서를 기준으로 데이터 가져오기: iloc 속성

In [157]:
titanic_df.iloc[0]

passengerId                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [158]:
titanic_df.iloc[0:5]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [159]:
titanic_df.iloc[0:10:3]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [160]:
titanic_df.iloc[:, [0, 2]]

     passengerId  pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
151          152       1
152          153       3
153          154       3
154          155       3
155          156       1

[156 rows x 2 columns]

In [161]:
titanic_df.iloc[1:5, [0, 2]]

   passengerId  pclass
1            2       1
2            3       3
3            4       1
4            5       3

In [162]:
titanic_df.iloc[1:5, 1:4]

   survived  pclass                                               name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

###피벗 테이블을 이용해 데이터 가져오기

In [163]:
titanic_df.pivot_table(index='pclass', columns='sex', values='survived')

sex       female      male
pclass
1       1.000000  0.142857
2       0.916667  0.166667
3       0.571429  0.131148

###그룹으로 묶어서 데이터 가져오기

In [164]:
titanic_df.head( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [165]:
titanic_df.groupby('survived').count( )

,passengerId,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
survived,,,,,,,,,,,
0,102,102,102,102,85,102,102,102,102,14,102
1,54,54,54,54,41,54,54,54,54,17,53

In [166]:
titanic_df.groupby('survived').mean( )

<ipython-input-166-4f1227463d5b>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  titanic_df.groupby('survived').mean( )

          passengerId    pclass        age     sibsp     parch       fare
survived
0           84.823529  2.490196  29.358824  0.666667  0.372549  27.271076
1           66.555556  2.296296  25.617805  0.518519  0.444444  29.693441

In [167]:
titanic_df.groupby('sex').sum( )

<ipython-input-167-3f1337ccb646>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  titanic_df.groupby('sex').sum( )

        passengerId  survived  pclass      age  sibsp  parch       fare
sex
female         3815        40     138  1150.00     49     29  1593.7958
male           8431        14     240  2395.83     47     33  2791.2998

In [168]:
titanic_df.groupby('sex')['survived'].mean( )

sex
female    0.714286
male      0.140000
Name: survived, dtype: float64

In [169]:
titanic_df.groupby(['sex', 'survived']).mean( )

<ipython-input-169-e1d4e0560ece>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  titanic_df.groupby(['sex', 'survived']).mean( )

                 passengerId    pclass        age     sibsp     parch  \
sex    survived
female 0           80.437500  2.937500  20.633333  1.437500  0.562500
       1           63.200000  2.275000  26.265625  0.650000  0.500000
male   0           85.639535  2.406977  31.228571  0.523256  0.337209
       1           76.142857  2.357143  23.314444  0.142857  0.285714

                      fare
sex    survived
female 0         18.883331
       1         32.291563
male   0         28.831587
       1         22.270236

##6. 데이터 재구조화하기
###stack과 unstack

In [170]:
df = titanic_df.groupby(['sex', 'survived']).mean()
df

<ipython-input-170-40a40d2d0d69>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = titanic_df.groupby(['sex', 'survived']).mean()

                 passengerId    pclass        age     sibsp     parch  \
sex    survived
female 0           80.437500  2.937500  20.633333  1.437500  0.562500
       1           63.200000  2.275000  26.265625  0.650000  0.500000
male   0           85.639535  2.406977  31.228571  0.523256  0.337209
       1           76.142857  2.357143  23.314444  0.142857  0.285714

                      fare
sex    survived
female 0         18.883331
       1         32.291563
male   0         28.831587
       1         22.270236

In [172]:
df.unstack('sex')

         passengerId             pclass                  age             \
sex           female       male  female      male     female       male
survived
0            80.4375  85.639535  2.9375  2.406977  20.633333  31.228571
1            63.2000  76.142857  2.2750  2.357143  26.265625  23.314444

           sibsp             parch                 fare
sex       female      male  female      male     female       male
survived
0         1.4375  0.523256  0.5625  0.337209  18.883331  28.831587
1         0.6500  0.142857  0.5000  0.285714  32.291563  22.270236

In [173]:
df.unstack('survived')

         passengerId               pclass                  age             \
survived           0          1         0         1          0          1
sex
female     80.437500  63.200000  2.937500  2.275000  20.633333  26.265625
male       85.639535  76.142857  2.406977  2.357143  31.228571  23.314444

             sibsp               parch                 fare
survived         0         1         0         1          0          1
sex
female    1.437500  0.650000  0.562500  0.500000  18.883331  32.291563
male      0.523256  0.142857  0.337209  0.285714  28.831587  22.270236

In [174]:
survived=df.unstack('survived')
survived_stack=survived.stack('survived')
survived_stack

                 passengerId    pclass        age     sibsp     parch  \
sex    survived
female 0           80.437500  2.937500  20.633333  1.437500  0.562500
       1           63.200000  2.275000  26.265625  0.650000  0.500000
male   0           85.639535  2.406977  31.228571  0.523256  0.337209
       1           76.142857  2.357143  23.314444  0.142857  0.285714

                      fare
sex    survived
female 0         18.883331
       1         32.291563
male   0         28.831587
       1         22.270236

###인덱스 초기화하기: reset_index 함수

In [175]:
df1=df.reset_index( )
df1

,sex,survived,passengerId,pclass,age,sibsp,parch,fare
0,female,0,80.437500,2.937500,20.633333,1.437500,0.562500,18.883331
1,female,1,63.200000,2.275000,26.265625,0.650000,0.500000,32.291563
2,male,0,85.639535,2.406977,31.228571,0.523256,0.337209,28.831587
3,male,1,76.142857,2.357143,23.314444,0.142857,0.285714,22.270236

In [176]:
df.reset_index(inplace=True)
df

,sex,survived,passengerId,pclass,age,sibsp,parch,fare
0,female,0,80.437500,2.937500,20.633333,1.437500,0.562500,18.883331
1,female,1,63.200000,2.275000,26.265625,0.650000,0.500000,32.291563
2,male,0,85.639535,2.406977,31.228571,0.523256,0.337209,28.831587
3,male,1,76.142857,2.357143,23.314444,0.142857,0.285714,22.270236

##7. 데이터프레임 합치기

In [177]:
import pandas as pd
url='https://github.com/sehakflower/data/blob/main/titanic_1309.xlsx?raw=true'
titanic=pd.read_excel(url, sheet_name='total')
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [178]:
train_1000=titanic.iloc[:1000]
test_309=titanic.iloc[1000:]
len(train_1000), len(test_309)

(1000, 309)

In [179]:
train_1000.to_csv('train_1000.csv')
test_309.to_csv('test_309.csv')

In [180]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [181]:
pd.read_csv('/content/train_1000.csv')

,Unnamed: 0,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,3,0,"Markoff, Mr. Marin",male,35.0000,0,0,349213,7.8958,NaN,C,NaN,NaN,NaN
996,996,3,0,"Markun, Mr. Johann",male,33.0000,0,0,349257,7.8958,NaN,S,NaN,NaN,NaN
997,997,3,1,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,C,NaN,NaN
998,998,3,0,"Matinoff, Mr. Nicola",male,NaN,0,0,349255,7.8958,NaN,C,NaN,NaN,NaN
999,999,3,1,"McCarthy, Miss. Catherine ""Katie""",female,NaN,0,0,383123,7.7500,NaN,Q,15 16,NaN,NaN

###데이터 합치기: concat 함수

In [182]:
total_df=pd.concat([train_1000, test_309]) # 옵션 없으면 axis=0
total_df=pd.concat([train_1000, test_309], axis=0) # 위아래로 붙일 때는 axis=0
total_df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [183]:
total_df=pd.concat([train_1000, test_309])
total_df=pd.concat([train_1000, test_309], axis=1)
total_df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,...,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.5,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.5,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.0,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.0,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN

###데이터프레임 병합  : merge 함수

In [184]:
df1=train_1000[['name', 'pclass', 'sex', 'age']]
df1

                                                name  pclass     sex      age
0                      Allen, Miss. Elisabeth Walton       1  female  29.0000
1                     Allison, Master. Hudson Trevor       1    male   0.9167
2                       Allison, Miss. Helen Loraine       1  female   2.0000
3               Allison, Mr. Hudson Joshua Creighton       1    male  30.0000
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1  female  25.0000
..                                               ...     ...     ...      ...
995                               Markoff, Mr. Marin       3    male  35.0000
996                               Markun, Mr. Johann       3    male  33.0000
997                          Masselmani, Mrs. Fatima       3  female      NaN
998                             Matinoff, Mr. Nicola       3    male      NaN
999                McCarthy, Miss. Catherine "Katie"       3  female      NaN

[1000 rows x 4 columns]

In [185]:
df2=train_1000[['name', 'survived']]
df2

                                                name  survived
0                      Allen, Miss. Elisabeth Walton         1
1                     Allison, Master. Hudson Trevor         1
2                       Allison, Miss. Helen Loraine         0
3               Allison, Mr. Hudson Joshua Creighton         0
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)         0
..                                               ...       ...
995                               Markoff, Mr. Marin         0
996                               Markun, Mr. Johann         0
997                          Masselmani, Mrs. Fatima         1
998                             Matinoff, Mr. Nicola         0
999                McCarthy, Miss. Catherine "Katie"         1

[1000 rows x 2 columns]

In [186]:
merge_inner=pd.merge(df1, df2)
merge_inner

,name,pclass,sex,age,survived
0,"Allen, Miss. Elisabeth Walton",1,female,29.0000,1
1,"Allison, Master. Hudson Trevor",1,male,0.9167,1
2,"Allison, Miss. Helen Loraine",1,female,2.0000,0
3,"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,0
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0
...,...,...,...,...,...
999,"Markoff, Mr. Marin",3,male,35.0000,0
1000,"Markun, Mr. Johann",3,male,33.0000,0
1001,"Masselmani, Mrs. Fatima",3,female,NaN,1
1002,"Matinoff, Mr. Nicola",3,male,NaN,0
1003,"McCarthy, Miss. Catherine ""Katie""",3,female,NaN,1

In [187]:
df2.loc[[0,2,3], ['name']] = ''
df2=df2[:10]
df1=df1[:10]
merge_inner=pd.merge(df1, df2, how='inner', on='name')
merge_inner

,name,pclass,sex,age,survived
0,"Allison, Master. Hudson Trevor",1,male,0.9167,1
1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0
2,"Anderson, Mr. Harry",1,male,48.0000,1
3,"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,1
4,"Andrews, Mr. Thomas Jr",1,male,39.0000,0
5,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,1
6,"Artagaveytia, Mr. Ramon",1,male,71.0000,0

In [188]:
merge_outer = pd.merge(df1,df2, how='outer',on='name')
merge_outer

,name,pclass,sex,age,survived
0,"Allen, Miss. Elisabeth Walton",1.0,female,29.0000,NaN
1,"Allison, Master. Hudson Trevor",1.0,male,0.9167,1.0
2,"Allison, Miss. Helen Loraine",1.0,female,2.0000,NaN
3,"Allison, Mr. Hudson Joshua Creighton",1.0,male,30.0000,NaN
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1.0,female,25.0000,0.0
5,"Anderson, Mr. Harry",1.0,male,48.0000,1.0
6,"Andrews, Miss. Kornelia Theodosia",1.0,female,63.0000,1.0
7,"Andrews, Mr. Thomas Jr",1.0,male,39.0000,0.0
8,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1.0,female,53.0000,1.0
9,"Artagaveytia, Mr. Ramon",1.0,male,71.0000,0.0
10,,NaN,NaN,NaN,1.0
11,,NaN,NaN,NaN,0.0
12,,NaN,NaN,NaN,0.0

In [189]:
merge_left=pd.merge(df1, df2, how='left', left_on='name', right_on='name')
merge_left

,name,pclass,sex,age,survived
0,"Allen, Miss. Elisabeth Walton",1,female,29.0000,NaN
1,"Allison, Master. Hudson Trevor",1,male,0.9167,1.0
2,"Allison, Miss. Helen Loraine",1,female,2.0000,NaN
3,"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,NaN
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0.0
5,"Anderson, Mr. Harry",1,male,48.0000,1.0
6,"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,1.0
7,"Andrews, Mr. Thomas Jr",1,male,39.0000,0.0
8,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,1.0
9,"Artagaveytia, Mr. Ramon",1,male,71.0000,0.0

In [190]:
merge_right=pd.merge(df1, df2, how='right', left_on='name', right_on='name')
merge_right

,name,pclass,sex,age,survived
0,,NaN,NaN,NaN,1
1,"Allison, Master. Hudson Trevor",1.0,male,0.9167,1
2,,NaN,NaN,NaN,0
3,,NaN,NaN,NaN,0
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1.0,female,25.0000,0
5,"Anderson, Mr. Harry",1.0,male,48.0000,1
6,"Andrews, Miss. Kornelia Theodosia",1.0,female,63.0000,1
7,"Andrews, Mr. Thomas Jr",1.0,male,39.0000,0
8,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1.0,female,53.0000,1
9,"Artagaveytia, Mr. Ramon",1.0,male,71.0000,0

###데이터프레임 결합  : join 함수

In [191]:
df2.loc[[1], ['name']]='Kildong, Mr. Hong'
df2=df2[:10]
df2

                                              name  survived
0                                                          1
1                                Kildong, Mr. Hong         1
2                                                          0
3                                                          0
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)         0
5                              Anderson, Mr. Harry         1
6                Andrews, Miss. Kornelia Theodosia         1
7                           Andrews, Mr. Thomas Jr         0
8    Appleton, Mrs. Edward Dale (Charlotte Lamson)         1
9                          Artagaveytia, Mr. Ramon         0

In [192]:
df1.set_index('name', inplace=True)
df2.set_index('name', inplace=True)

In [81]:
df1

                                                 pclass     sex      age
name
Allen, Miss. Elisabeth Walton                         1  female  29.0000
Allison, Master. Hudson Trevor                        1    male   0.9167
Allison, Miss. Helen Loraine                          1  female   2.0000
Allison, Mr. Hudson Joshua Creighton                  1    male  30.0000
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1  female  25.0000
...                                                 ...     ...      ...
Markoff, Mr. Marin                                    3    male  35.0000
Markun, Mr. Johann                                    3    male  33.0000
Masselmani, Mrs. Fatima                               3  female      NaN
Matinoff, Mr. Nicola                                  3    male      NaN
McCarthy, Miss. Catherine "Katie"                     3  female      NaN

[1000 rows x 3 columns]

In [193]:
df2

                                                 survived
name
                                                        1
Kildong, Mr. Hong                                       1
                                                        0
                                                        0
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)         0
Anderson, Mr. Harry                                     1
Andrews, Miss. Kornelia Theodosia                       1
Andrews, Mr. Thomas Jr                                  0
Appleton, Mrs. Edward Dale (Charlotte Lamson)           1
Artagaveytia, Mr. Ramon                                 0

In [194]:
df1.join(df2)

,pclass,sex,age,survived
name,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,NaN
"Allison, Master. Hudson Trevor",1,male,0.9167,NaN
"Allison, Miss. Helen Loraine",1,female,2.0000,NaN
"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,NaN
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0.0
"Anderson, Mr. Harry",1,male,48.0000,1.0
"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,1.0
"Andrews, Mr. Thomas Jr",1,male,39.0000,0.0
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,1.0
"Artagaveytia, Mr. Ramon",1,male,71.0000,0.0

In [195]:
df1.join(df2, how='inner')

,pclass,sex,age,survived
name,,,,
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0,0
"Anderson, Mr. Harry",1,male,48.0,1
"Andrews, Miss. Kornelia Theodosia",1,female,63.0,1
"Andrews, Mr. Thomas Jr",1,male,39.0,0
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0,1
"Artagaveytia, Mr. Ramon",1,male,71.0,0

In [196]:
df2.join(df1)

,survived,pclass,sex,age
name,,,,
,1,NaN,NaN,NaN
,0,NaN,NaN,NaN
,0,NaN,NaN,NaN
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",0,1.0,female,25.0
"Anderson, Mr. Harry",1,1.0,male,48.0
"Andrews, Miss. Kornelia Theodosia",1,1.0,female,63.0
"Andrews, Mr. Thomas Jr",0,1.0,male,39.0
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,1.0,female,53.0
"Artagaveytia, Mr. Ramon",0,1.0,male,71.0
"Kildong, Mr. Hong",1,NaN,NaN,NaN

In [197]:
titanic_df[titanic_df['age']>70] # 70세 이상인 승객 검색

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

In [198]:
titanic_df[titanic_df['age']<3] # 3세 미만인 승객 검색

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.075,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.125,NaN,Q
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.000,NaN,S
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.275,NaN,S

In [199]:
titanic_df[titanic_df['age']<3]['name'] # 3세 미만 승객의 이름 검색

7         Palsson, Master. Gosta Leonard
16                  Rice, Master. Eugene
78         Caldwell, Master. Alden Gates
119    Andersson, Miss. Ellis Anna Maria
Name: name, dtype: object

In [200]:
titanic_df[titanic_df['age']<3][['age', 'name']]

      age                               name
7    2.00     Palsson, Master. Gosta Leonard
16   2.00               Rice, Master. Eugene
78   0.83      Caldwell, Master. Alden Gates
119  2.00  Andersson, Miss. Ellis Anna Maria

##2. loc 속성으로 조건 검색하기

In [201]:
titanic_df.loc[titanic_df['age']<3]['name'] # 3세 미만 승객의 이름 검색

7         Palsson, Master. Gosta Leonard
16                  Rice, Master. Eugene
78         Caldwell, Master. Alden Gates
119    Andersson, Miss. Ellis Anna Maria
Name: name, dtype: object

In [202]:
titanic_df.loc[titanic_df['age']<3, 'name':'sex']

                                  name     sex
7       Palsson, Master. Gosta Leonard    male
16                Rice, Master. Eugene    male
78       Caldwell, Master. Alden Gates    male
119  Andersson, Miss. Ellis Anna Maria  female

In [203]:
titanic_df.loc[titanic_df['age']<3, ['name', 'sex']]

                                  name     sex
7       Palsson, Master. Gosta Leonard    male
16                Rice, Master. Eugene    male
78       Caldwell, Master. Alden Gates    male
119  Andersson, Miss. Ellis Anna Maria  female

##3. isin 함수로 조건 검색하기

In [204]:
my_condition=['male']
my_condition

['male']

In [205]:
titanic_df['sex'].isin(my_condition)

0       True
1      False
2      False
3      False
4       True
       ...
151    False
152     True
153     True
154     True
155     True
Name: sex, Length: 156, dtype: bool

In [206]:
titanic_df['name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
151                    Pears, Mrs. Thomas (Edith Wearne)
152                                     Meo, Mr. Alfonzo
153                      van Billiard, Mr. Austin Blyler
154                                Olsen, Mr. Ole Martin
155                          Williams, Mr. Charles Duane
Name: name, Length: 156, dtype: object

In [207]:
my_condition1=['Braund, Mr. Owen Harris', 'Williams, Mr. Charles Duane']
my_condition1

['Braund, Mr. Owen Harris', 'Williams, Mr. Charles Duane']

In [208]:
titanic_df['name'].isin(my_condition1)

0       True
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154    False
155     True
Name: name, Length: 156, dtype: bool

##4. isin 함수와 loc 속성으로 조건 검색하기

In [209]:
titanic_df.loc[titanic_df['name'].isin(my_condition1)]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [210]:
titanic_df.loc[titanic_df['name'].isin(my_condition1), 'age']

0      22.0
155    51.0
Name: age, dtype: float64

In [211]:
titanic_df.loc[titanic_df['name'].isin(my_condition1), 'name']

0          Braund, Mr. Owen Harris
155    Williams, Mr. Charles Duane
Name: name, dtype: object

In [212]:
titanic_df.loc[titanic_df['name'].isin(my_condition1), 'pclass':'age']

     pclass                         name   sex   age
0         3      Braund, Mr. Owen Harris  male  22.0
155       1  Williams, Mr. Charles Duane  male  51.0

In [213]:
titanic_df.loc[titanic_df['name'].isin(my_condition1), ['pclass', 'age']]

     pclass   age
0         3  22.0
155       1  51.0